package main

import (
	"bytes"
	"strings"
	"testing"
)

func TestGenCmd_Go(t *testing.T) {
	cmd := newRootCmd("test")
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"gen", "--to", "go", "testdata/county.yammm"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("gen: %v\noutput:\n%s", err, out.String())
	}
	got := out.String()
	if !strings.Contains(got, "// Code generated by yammm. DO NOT EDIT.") {
		t.Errorf("missing generated header:\n%s", got)
	}
	if !strings.Contains(got, "type County struct") {
		t.Errorf("missing County struct:\n%s", got)
	}
}
