package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/simon-lentz/yammm/cmd/yammm/internal/cli"
)

func TestGenCmd_Go(t *testing.T) {
	cmd := newRootCmd("test")
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"gen", "--to", "go", "testdata/county.yammm"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("gen: %v\noutput:\n%s", err, out.String())
	}
	got := out.String()
	if !strings.Contains(got, "// Code generated by yammm. DO NOT EDIT.") {
		t.Errorf("missing generated header:\n%s", got)
	}
	if !strings.Contains(got, "type County struct") {
		t.Errorf("missing County struct:\n%s", got)
	}
}

// TestGenCmd_OutputFile covers --output: generated code is written to the named file,
// not stdout.
func TestGenCmd_OutputFile(t *testing.T) {
	out := filepath.Join(t.TempDir(), "county_gen.go")
	cmd := newRootCmd("test")
	var buf bytes.Buffer
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs([]string{"gen", "--to", "go", "--output", out, "testdata/county.yammm"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("gen --output: %v\noutput:\n%s", err, buf.String())
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read --output file: %v", err)
	}
	if !bytes.Contains(data, []byte("type County struct")) {
		t.Errorf("--output file missing County struct:\n%s", data)
	}
	if strings.Contains(buf.String(), "type County struct") {
		t.Errorf("with --output set, code must go to the file, not stdout:\n%s", buf.String())
	}
}

// TestGenCmd_PackageOverride covers --package: the generated package clause uses the
// override rather than the schema-derived name.
func TestGenCmd_PackageOverride(t *testing.T) {
	cmd := newRootCmd("test")
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"gen", "--to", "go", "--package", "custompkg", "testdata/county.yammm"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("gen --package: %v\noutput:\n%s", err, out.String())
	}
	if !strings.Contains(out.String(), "package custompkg") {
		t.Errorf("--package custompkg not honored:\n%s", out.String())
	}
}

// TestGenCmd_Initialisms covers --initialisms end-to-end: jwt is not a default golint
// initialism, so --initialisms JWT upper-cases jwt_token's Go field to JWTToken.
func TestGenCmd_Initialisms(t *testing.T) {
	cmd := newRootCmd("test")
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"gen", "--to", "go", "--initialisms", "JWT", "testdata/session.yammm"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("gen --initialisms: %v\noutput:\n%s", err, out.String())
	}
	if !strings.Contains(out.String(), "JWTToken") {
		t.Errorf("--initialisms JWT not applied (expected JWTToken):\n%s", out.String())
	}
}

// TestGenCmd_BadTarget covers the unsupported-target path: --to must be "go"; anything
// else is a usage error (ExitUsage).
func TestGenCmd_BadTarget(t *testing.T) {
	cmd := newRootCmd("test")
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"gen", "--to", "rust", "testdata/county.yammm"})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("expected an error for an unsupported --to target")
	}
	var exitErr *cli.ExitError
	if !errors.As(err, &exitErr) || exitErr.Code != cli.ExitUsage {
		t.Errorf("expected a cli.ExitError with ExitUsage, got %T: %v", err, err)
	}
}
