package trace

import "context"

// contextKey is an unexported type for context keys to prevent collisions
// with keys defined in other packages.
type contextKey struct{ name string }

// requestIDKey is the context key for the request ID.
var requestIDKey = contextKey{"request_id"}

// WithRequestID returns a context with the given request ID attached.
// The request ID will be automatically included in logs via the [Op] runner.
//
// Request IDs are caller-supplied identifiers for correlating log entries
// across a single request or operation. Unlike trace IDs, they are typically
// provided by the service layer rather than generated by the library.
//
// If id is empty, the request ID is still stored (use [RequestIDFrom] to
// distinguish "empty string" from "not set").
func WithRequestID(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, requestIDKey, id)
}

// RequestIDFrom extracts the request ID from the context, if present.
// Returns the request ID and true if set, or "" and false if not set.
//
// Note: If [WithRequestID] was called with an empty string, this returns
// ("", true) to distinguish from the "not set" case.
func RequestIDFrom(ctx context.Context) (string, bool) {
	v, ok := ctx.Value(requestIDKey).(string)
	if !ok {
		return "", false
	}
	return v, true
}
