package snapshot

import (
	"bytes"
	"encoding/json"
	"math"
	"strings"
	"testing"

	"github.com/simon-lentz/yammm/schema"
)

// wireFloat.MarshalJSON is a copy of encoding/json's float encoder, kept for
// its cost. This holds the two in lockstep so the copy cannot drift, and it is
// the only coverage of the exponent branch and the e-09 → e-9 trim.
func TestWireFloat_MatchesEncodingJSON(t *testing.T) {
	t.Parallel()

	vals := []float64{
		0, 1, -1, 2.5, 0.1, 1860000, math.Pi,
		math.SmallestNonzeroFloat64, math.MaxFloat64,
		1e-6, 9.999999e-7, 1e-7, 1e-9, 1e-10, 1e20, 1e21, 1.0000001e21,
	}
	for e := -320; e <= 308; e++ {
		p := math.Pow(10, float64(e))
		vals = append(vals, p, -p, p*3, p/7)
	}
	for i := range 20000 {
		vals = append(vals, float64(i), float64(i)/7, -float64(i)*1e-8)
	}

	var sawExponent, sawTrim, sawSuffix bool
	for _, v := range vals {
		if math.IsInf(v, 0) || math.IsNaN(v) {
			continue // generated by overflow; the non-finite path is its own test
		}
		got, err := wireFloat(v).MarshalJSON()
		if err != nil {
			t.Fatalf("wireFloat(%v).MarshalJSON: %v", v, err)
		}
		want, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("json.Marshal(%v): %v", v, err)
		}
		if !bytes.ContainsAny(want, ".eE") {
			want = append(want, '.', '0')
			sawSuffix = true
		}
		if !bytes.Equal(got, want) {
			t.Fatalf("wireFloat(%v) = %s, encoding/json + suffix = %s", v, got, want)
		}
		if bytes.ContainsAny(got, "eE") {
			sawExponent = true
			if bytes.Contains(got, []byte("e-9")) || bytes.Contains(got, []byte("e+9")) {
				sawTrim = true
			}
		}
	}

	// Corpus floor: without these the comparison above can pass vacuously.
	if !sawExponent {
		t.Error("corpus never reached the exponent branch")
	}
	if !sawTrim {
		t.Error("corpus never reached a single-digit exponent, where the trim applies")
	}
	if !sawSuffix {
		t.Error("corpus never reached a whole float, where the .0 suffix applies")
	}
}

// A non-finite value under a Float constraint errors rather than emitting
// invalid JSON. Validation rejects NaN and Inf, so this path is reachable only
// from a caller-assembled snapshot.
func TestWireFloat_NonFiniteErrors(t *testing.T) {
	t.Parallel()
	for _, v := range []float64{math.NaN(), math.Inf(1), math.Inf(-1)} {
		got, err := wireFloat(v).MarshalJSON()
		if err == nil {
			t.Errorf("wireFloat(%v) marshalled to %s, want an error", v, got)
			continue
		}
		if !strings.Contains(err.Error(), "unsupported value") {
			t.Errorf("wireFloat(%v) error = %q, want it to name an unsupported value", v, err)
		}
	}
}

// Every numeric Go type a caller-assembled snapshot can carry reaches
// wireFloat. A type that falls through emits int-shaped and narrows on the
// next load, which is the narrowing the emitter exists to remove.
func TestWireNumeric_EveryNumericKind(t *testing.T) {
	t.Parallel()
	type namedFloat float64
	type namedInt int32

	cases := []struct {
		name string
		in   any
	}{
		{"float64", float64(2)},
		{"float32", float32(2)},
		{"int", int(2)},
		{"int8", int8(2)},
		{"int16", int16(2)},
		{"int32", int32(2)},
		{"int64", int64(2)},
		{"uint", uint(2)},
		{"uint8", uint8(2)},
		{"uint16", uint16(2)},
		{"uint32", uint32(2)},
		{"uint64", uint64(2)},
		{"named float", namedFloat(2)},
		{"named int", namedInt(2)},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := wireNumeric(tc.in)
			f, ok := got.(wireFloat)
			if !ok {
				t.Fatalf("wireNumeric(%T) = %T, want wireFloat — this type still emits int-shaped", tc.in, got)
			}
			if float64(f) != 2 {
				t.Fatalf("wireNumeric(%T) = %v, want 2", tc.in, float64(f))
			}
			b, err := f.MarshalJSON()
			if err != nil {
				t.Fatalf("MarshalJSON: %v", err)
			}
			if string(b) != "2.0" {
				t.Errorf("emitted %s, want 2.0", b)
			}
		})
	}
}

// A non-numeric value passes through untouched: Load never re-validates, so a
// hand-crafted document can put anything in a float position.
func TestWireNumeric_NonNumericPassesThrough(t *testing.T) {
	t.Parallel()
	for _, v := range []any{"two", true, nil, []any{1.0}, map[string]any{}} {
		if got := wireNumeric(v); got != nil && v == nil {
			t.Errorf("wireNumeric(nil) = %v, want nil", got)
		} else if v != nil {
			if _, wrapped := wireNumeric(v).(wireFloat); wrapped {
				t.Errorf("wireNumeric(%T) wrapped a non-numeric value as a float", v)
			}
		}
	}
}

// Healing turns on exact convertibility, not on magnitude. An integer beyond
// 2^53 that converts exactly did come from a whole float and must heal; one
// that does not convert exactly cannot have, and healing it would invent
// precision.
func TestExactWireInt_TurnsOnConvertibility(t *testing.T) {
	t.Parallel()

	exact := []int64{
		0, 1, -1, 1 << 53, -(1 << 53),
		1 << 62, -(1 << 62), // beyond 2^53 and exactly representable
		1_000_000_000_000_000_000,
		math.MinInt64, // -2^63 is exactly representable
	}
	for _, n := range exact {
		f, ok := exactWireInt(n)
		if !ok {
			t.Errorf("exactWireInt(%d) = not exact, want exact — a narrowed whole float here never heals", n)
			continue
		}
		if int64(f) != n {
			t.Errorf("exactWireInt(%d) = %v, which converts back to %d", n, f, int64(f))
		}
	}

	inexact := []int64{
		(1 << 53) + 1, -((1 << 53) + 1),
		(1 << 62) + 1,
		math.MaxInt64, // float64 rounds it up to 2^63
	}
	for _, n := range inexact {
		if _, ok := exactWireInt(n); ok {
			t.Errorf("exactWireInt(%d) = exact, want inexact — healing it would change the value", n)
		}
	}
}

func TestExactWireUint_TurnsOnConvertibility(t *testing.T) {
	t.Parallel()
	if _, ok := exactWireUint(1 << 63); !ok {
		t.Error("exactWireUint(2^63) = inexact, want exact")
	}
	if _, ok := exactWireUint(math.MaxUint64); ok {
		t.Error("exactWireUint(MaxUint64) = exact, want inexact — float64 rounds it up to 2^64")
	}
}

// wireElems reaches a vector or list position whatever container the caller
// built. []byte is the case worth pinning: encoding/json renders it as a
// base64 string, which is the wrong shape for a declared list, so the widened
// arm changes the wire for a caller-assembled snapshot.
func TestWireElems_ReachesEveryContainer(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		in   any
	}{
		{"byte slice", []byte{1, 2, 3}},
		{"float32 slice", []float32{1, 2, 3}},
		{"int slice", []int{1, 2, 3}},
		{"array", [3]float64{1, 2, 3}},
		{"any slice", []any{float64(1), float64(2), float64(3)}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := wireValue(tc.in, schema.VectorConstraint{})
			elems, ok := got.([]any)
			if !ok {
				t.Fatalf("wireValue over %T returned %T, want []any — the container never reached the vector arm", tc.in, got)
			}
			if len(elems) != 3 {
				t.Fatalf("got %d elements, want 3", len(elems))
			}
			for i, e := range elems {
				if _, ok := e.(wireFloat); !ok {
					t.Errorf("element %d is %T, want wireFloat — it would emit int-shaped", i, e)
				}
			}
		})
	}

	// A non-container under the same constraint passes through untouched, or
	// the assertions above would hold for anything.
	if got := wireValue("not a vector", schema.VectorConstraint{}); got != "not a vector" {
		t.Errorf("wireValue over a string returned %#v, want it untouched", got)
	}
}

// The exactness guard turns on convertibility, so a value it cannot represent
// passes through. Driving every kind at 2 alone never reaches that arm.
func TestWireNumeric_InexactValuesPassThrough(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		in      any
		wrapped bool
	}{
		{"int64 exactly convertible beyond 2^53", int64(1) << 62, true},
		{"int64 not exactly convertible", int64(1)<<62 + 1, false},
		{"MaxInt64", int64(math.MaxInt64), false},
		{"uint64 not exactly convertible", uint64(1)<<63 + 1, false},
		{"negative exactly convertible", int64(math.MinInt64), true},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := wireNumeric(tc.in)
			_, wrapped := got.(wireFloat)
			if wrapped != tc.wrapped {
				t.Errorf("wireNumeric(%v) wrapped = %v, want %v", tc.in, wrapped, tc.wrapped)
			}
		})
	}
}
