// Package grammar contains the ANTLR4-generated parser for the YAMMM DSL.
//
// This file exists solely to host the go:generate directive for grammar generation.
// The actual parser code is generated by ANTLR4 from YammmGrammar.g4. Run
// "go generate ./..." from the repo root or "make generate-grammars" to regenerate.
package grammar

//go:generate sh -c "cd ../../.. && make generate-grammars"
