// Code generated by yammm. DO NOT EDIT.
package temporal

import (
	"encoding/json"
	"time"
)

// marshalTemporal renders t through layout as a JSON string.
func marshalTemporal(t time.Time, layout string) ([]byte, error) {
	return json.Marshal(t.Format(layout))
}

// unmarshalTemporal parses a JSON string through layout into *dst. A JSON
// null leaves *dst unchanged, as time.Time's own UnmarshalJSON does.
func unmarshalTemporal(b []byte, layout string, dst *time.Time) error {
	if string(b) == "null" {
		return nil
	}
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	t, err := time.Parse(layout, s)
	if err != nil {
		return err
	}
	*dst = t
	return nil
}

// Date is exchanged as a JSON string in the layout "2006-01-02".
type Date struct{ time.Time }

const dateLayout = "2006-01-02"

func (v Date) MarshalJSON() ([]byte, error) { return marshalTemporal(v.Time, dateLayout) }

func (v *Date) UnmarshalJSON(b []byte) error { return unmarshalTemporal(b, dateLayout, &v.Time) }

// Timestamp20060102150405 is exchanged as a JSON string in the layout "2006-01-02 15:04:05".
type Timestamp20060102150405 struct{ time.Time }

const timestamp20060102150405Layout = "2006-01-02 15:04:05"

func (v Timestamp20060102150405) MarshalJSON() ([]byte, error) {
	return marshalTemporal(v.Time, timestamp20060102150405Layout)
}

func (v *Timestamp20060102150405) UnmarshalJSON(b []byte) error {
	return unmarshalTemporal(b, timestamp20060102150405Layout, &v.Time)
}

// Timestamp20060102T150405000000000Z0700 is exchanged as a JSON string in the layout "2006-01-02T15:04:05.000000000Z07:00".
type Timestamp20060102T150405000000000Z0700 struct{ time.Time }

const timestamp20060102T150405000000000Z0700Layout = "2006-01-02T15:04:05.000000000Z07:00"

func (v Timestamp20060102T150405000000000Z0700) MarshalJSON() ([]byte, error) {
	return marshalTemporal(v.Time, timestamp20060102T150405000000000Z0700Layout)
}

func (v *Timestamp20060102T150405000000000Z0700) UnmarshalJSON(b []byte) error {
	return unmarshalTemporal(b, timestamp20060102T150405000000000Z0700Layout, &v.Time)
}

// Day is exchanged as a JSON string in the layout "2006-01-02".
type Day struct{ time.Time }

const dayLayout = "2006-01-02"

func (v Day) MarshalJSON() ([]byte, error) { return marshalTemporal(v.Time, dayLayout) }

func (v *Day) UnmarshalJSON(b []byte) error { return unmarshalTemporal(b, dayLayout, &v.Time) }

type Stamp struct{ time.Time }

// Wall is exchanged as a JSON string in the layout "2006-01-02 15:04:05".
type Wall struct{ time.Time }

const wallLayout = "2006-01-02 15:04:05"

func (v Wall) MarshalJSON() ([]byte, error) { return marshalTemporal(v.Time, wallLayout) }

func (v *Wall) UnmarshalJSON(b []byte) error { return unmarshalTemporal(b, wallLayout, &v.Time) }

type Reading struct {
	At Timestamp20060102150405 `json:"at"`
	On *Date                   `json:"on,omitempty"`
}

type Sensor struct {
	ID             string                                 `json:"id"`
	Installed      Date                                   `json:"installed"`
	Decommissioned *Date                                  `json:"decommissioned,omitempty"`
	CreatedAt      time.Time                              `json:"created_at"`
	SeenWall       *Timestamp20060102150405               `json:"seen_wall,omitempty"`
	SeenAt         Timestamp20060102T150405000000000Z0700 `json:"seen_at"`
	Day            *Day                                   `json:"day,omitempty"`
	Stamp          *Stamp                                 `json:"stamp,omitempty"`
	Wall           *Wall                                  `json:"wall,omitempty"`
	Days           []Date                                 `json:"days,omitempty"`
	Walls          []Timestamp20060102150405              `json:"walls,omitempty"`
	HasReading     []*Reading                             `json:"has_reading,omitempty"`
}

type Graph struct {
	Sensor []*Sensor `json:"Sensor,omitempty"`
}

// serializedSources holds every source in the import closure, keyed by
// module-root-relative path, as verbatim .yammm text. Read it through
// SerializedSources below.
var serializedSources = map[string]string{
	"temporal.yammm": "schema \"temporal\"\n\ntype Day   = Date\ntype Stamp = Timestamp\ntype Wall  = Timestamp[\"2006-01-02 15:04:05\"]\n\npart type Reading {\n\tat Timestamp[\"2006-01-02 15:04:05\"] required\n\ton Date\n}\n\ntype Sensor {\n\tid             String primary\n\tinstalled      Date required\n\tdecommissioned Date\n\tcreated_at     Timestamp required\n\tseen_wall      Timestamp[\"2006-01-02 15:04:05\"]\n\tseen_at        Timestamp[\"2006-01-02T15:04:05.000000000Z07:00\"] required\n\tday            Day\n\tstamp          Stamp\n\twall           Wall\n\tdays           List<Date>\n\twalls          List<Timestamp[\"2006-01-02 15:04:05\"]>\n\t*-> HAS_READING (many) Reading\n}\n",
}

// SerializedEntry is the entry-point key into SerializedSources.
const SerializedEntry = "temporal.yammm"

// SerializedSources returns every source in the import closure, keyed by
// module-root-relative path. Re-load with:
//
//	schema.LoadSourcesWithEntry(ctx, SerializedSources(), SerializedEntry, "",
//		schema.WithSourcesOnly(), schema.WithSyntheticRoot("embedded://your-app"))
//
// The synthetic root is what keeps the loaded type identities stable. Passing
// module root "." instead also re-loads, but "." canonicalizes against the
// process working directory, which then lands inside every TypeID.
func SerializedSources() map[string][]byte {
	m := make(map[string][]byte, len(serializedSources))
	for k, v := range serializedSources {
		m[k] = []byte(v)
	}
	return m
}

const SchemaHash = "sha256:4946f0eb551f3dd057f2ed824df02616de0b33b720957dce8ea33a6b797ec160"
