package jschema

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/simon-lentz/yammm/schema"
)

// defaultDescription is the emitted document's top-level description when
// WithDescription is not given.
const defaultDescription = "Instance-data authoring schema generated by yammm. " +
	"Describes the JSON object form accepted by `yammm check`: one key per " +
	"concrete type, each an array of instances."

// Option configures Marshal.
type Option func(*config)

type config struct {
	schemaID    string
	title       string
	description string
}

// WithSchemaID sets the emitted document's "$id". When unset, "$id" is
// omitted entirely — JSON Schema 2020-12 makes it optional and there is no
// meaningful default URI for an arbitrary schema.
func WithSchemaID(uri string) Option {
	return func(c *config) { c.schemaID = uri }
}

// WithTitle overrides the document title (default: the schema name).
func WithTitle(title string) Option {
	return func(c *config) { c.title = title }
}

// WithDescription overrides the generated top-level description.
func WithDescription(text string) Option {
	return func(c *config) { c.description = text }
}

// Marshal renders a loaded, resolved schema (and its import closure) as a
// single self-contained JSON Schema draft 2020-12 document describing the
// instance-data JSON object form the yammm instance layer accepts. Output is
// deterministic — byte-identical across runs and machines — and validated
// before return: the bytes must parse as JSON and every "$ref" must resolve
// to an emitted "$defs" entry; a failure there is a generator bug surfaced
// as an error, never emitted output.
func Marshal(s *schema.Schema, opts ...Option) ([]byte, error) {
	cfg := config{}
	for _, o := range opts {
		o(&cfg)
	}
	table, err := buildDefsTable(s)
	if err != nil {
		return nil, err
	}
	doc, defKeys, err := buildDocument(s, table, cfg)
	if err != nil {
		return nil, err
	}
	out := renderDocument(doc)
	if err := selfCheck(out, defKeys); err != nil {
		return nil, err
	}
	return out, nil
}

// selfCheck guards Marshal's output contract: the bytes are valid JSON and
// every emitted "$ref" is a "#/$defs/<key>" pointer resolving to an emitted
// $defs entry. A failure is a generator bug surfaced as an error, never
// emitted output.
func selfCheck(out []byte, defKeys map[string]bool) error {
	var doc any
	if err := json.Unmarshal(out, &doc); err != nil {
		return fmt.Errorf("jschema: self-check: emitted document is not valid JSON: %w", err)
	}
	return checkRefs(doc, defKeys)
}

// checkRefs walks a decoded document and verifies every "$ref" member
// resolves. Reference tokens are unescaped per RFC 6901 ("~1" -> "/" then
// "~0" -> "~") before the $defs lookup, mirroring the escaping refTo
// applies. No emitted property is ever named "$ref" (wire field names come
// from the DSL grammar, which cannot produce a "$"), so every "$ref" key in
// the document is a reference.
func checkRefs(v any, defKeys map[string]bool) error {
	switch x := v.(type) {
	case map[string]any:
		if ref, ok := x["$ref"]; ok {
			s, ok := ref.(string)
			if !ok {
				return fmt.Errorf("jschema: self-check: non-string $ref value %v", ref)
			}
			key, ok := strings.CutPrefix(s, "#/$defs/")
			if !ok {
				return fmt.Errorf("jschema: self-check: $ref %q is not a #/$defs/ pointer", s)
			}
			key = strings.ReplaceAll(strings.ReplaceAll(key, "~1", "/"), "~0", "~")
			if !defKeys[key] {
				return fmt.Errorf("jschema: self-check: $ref %q resolves to no emitted $defs entry", s)
			}
		}
		for _, member := range x {
			if err := checkRefs(member, defKeys); err != nil {
				return err
			}
		}
	case []any:
		for _, elem := range x {
			if err := checkRefs(elem, defKeys); err != nil {
				return err
			}
		}
	}
	return nil
}
