package jschema

import (
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"slices"

	"github.com/simon-lentz/yammm/schema"
)

// defaultDescription is the emitted document's top-level description.
const defaultDescription = "Instance-data authoring schema generated by yammm. " +
	"Describes the JSON object form yammm reads: one key per type whose instances " +
	"a data file lists at the top level, each an array of instances. " +
	"It does not reproduce yammm's validation: `yammm check` gives the verdict on a file."

// Option configures Marshal.
type Option func(*config)

type config struct {
	schemaID string
}

// WithSchemaID sets the emitted document's "$id". When unset, "$id" is
// omitted entirely — JSON Schema 2020-12 makes it optional and there is no
// meaningful default URI for an arbitrary schema.
func WithSchemaID(uri string) Option {
	return func(c *config) { c.schemaID = uri }
}

// Marshal renders a loaded, resolved schema (and its import closure) as a
// single self-contained JSON Schema draft 2020-12 document describing the
// instance-data JSON object form the yammm instance layer accepts. Output is
// deterministic — byte-identical across runs and machines — and validated
// before return: the bytes must parse as JSON and every "$ref" must resolve
// to an entry of the "$defs" object those bytes hold; a failure there is a
// generator bug surfaced as an error, never emitted output.
func Marshal(s *schema.Schema, opts ...Option) ([]byte, error) {
	cfg := config{}
	for _, o := range opts {
		o(&cfg)
	}
	table, err := buildDefsTable(s)
	if err != nil {
		return nil, err
	}
	doc, err := buildDocument(s, table, cfg)
	if err != nil {
		return nil, err
	}
	return finish(renderDocument(doc))
}

// finish runs selfCheck over the rendered document and returns it. Marshal
// returns only what finish returns, so the check cannot be bypassed without
// losing the output.
func finish(out []byte) ([]byte, error) {
	if err := selfCheck(out); err != nil {
		return nil, err
	}
	return out, nil
}

// selfCheck guards Marshal's output contract: the bytes are valid JSON and
// every "$ref" is a "#/$defs/<key>" pointer naming a member of the top-level
// "$defs" object decoded from those same bytes, as a validator resolves it. A
// failure is a generator bug surfaced as an error, never emitted output.
func selfCheck(out []byte) error {
	var doc any
	if err := json.Unmarshal(out, &doc); err != nil {
		return fmt.Errorf("jschema: self-check: emitted document is not valid JSON: %w", err)
	}
	root, ok := doc.(map[string]any)
	if !ok {
		return errors.New("jschema: self-check: emitted document is not a JSON object")
	}
	var defs map[string]any
	if d, ok := root["$defs"].(map[string]any); ok {
		defs = d
	}
	return checkRefs(doc, defs)
}

// checkRefs walks a decoded document and verifies every "$ref" member names a
// member of defs, decoding each as [refKey] does. No emitted property is ever
// named "$ref" (wire field names come from the DSL grammar, which cannot
// produce a "$"), so every "$ref" key in the document is a reference. Members
// are walked in sorted key order, so a document holding several broken
// references reports the same one on every run.
func checkRefs(v any, defs map[string]any) error {
	switch x := v.(type) {
	case map[string]any:
		if ref, ok := x["$ref"]; ok {
			s, ok := ref.(string)
			if !ok {
				return fmt.Errorf("jschema: self-check: non-string $ref value %v", ref)
			}
			key, err := refKey(s)
			if err != nil {
				return fmt.Errorf("jschema: self-check: %w", err)
			}
			if _, ok := defs[key]; !ok {
				return fmt.Errorf("jschema: self-check: $ref %q resolves to no emitted $defs entry", s)
			}
		}
		for _, k := range slices.Sorted(maps.Keys(x)) {
			if err := checkRefs(x[k], defs); err != nil {
				return err
			}
		}
	case []any:
		for _, elem := range x {
			if err := checkRefs(elem, defs); err != nil {
				return err
			}
		}
	}
	return nil
}
