package gogen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"maps"
	"strings"

	"github.com/simon-lentz/yammm/location"
	"github.com/simon-lentz/yammm/schema"
)

const generatedHeader = "// Code generated by yammm. DO NOT EDIT.\n"

// Option configures Marshal.
type Option func(*config)

type config struct {
	packageName string
	initialisms []string // extra acronyms to upper-case, merged with the default set
}

// WithPackageName overrides the generated package name (default: derived from
// the schema name).
func WithPackageName(name string) Option {
	return func(c *config) { c.packageName = name }
}

// WithInitialisms registers additional acronyms (e.g. "GUID", "JWT") that the
// name-mapper upper-cases wholesale in exported Go identifiers. They MERGE with
// gogen's default golint set (they do not replace it) and are matched
// case-insensitively. This is how a downstream code generator injects its own
// domain vocabulary without that vocabulary ever living in yammm.
func WithInitialisms(names ...string) Option {
	return func(c *config) { c.initialisms = append(c.initialisms, names...) }
}

// defaultInitialisms is gogen's base acronym set: the canonical golint
// commonInitialisms list (github.com/golang/lint), lower-cased for the
// case-insensitive lookup ToUpperCamelInitialisms performs. yammm owns only this
// neutral, domain-free set; consumer-specific acronyms arrive via WithInitialisms
// and never live in yammm source.
//
// Caveat: ToUpperCamelInitialisms splits on letter/digit boundaries, so a
// digit-bearing initialism ("utf8" tokenizes to "utf","8") cannot match as a unit.
// "utf8" is listed for golint parity but only letter-only initialisms are
// effective. ("db" is intentionally absent — it is not in golint's canonical list;
// a consumer that wants it adds it via WithInitialisms.)
//
//nolint:gochecknoglobals // Intentional: static lookup table for name mapping.
var defaultInitialisms = map[string]bool{
	"acl": true, "api": true, "ascii": true, "cpu": true, "css": true,
	"dns": true, "eof": true, "guid": true, "html": true, "http": true,
	"https": true, "id": true, "ip": true, "json": true, "lhs": true,
	"qps": true, "ram": true, "rhs": true, "rpc": true, "sla": true,
	"smtp": true, "sql": true, "ssh": true, "tcp": true, "tls": true,
	"ttl": true, "udp": true, "ui": true, "uid": true, "uuid": true,
	"uri": true, "url": true, "utf8": true, "vm": true, "xml": true,
	"xmpp": true, "xsrf": true, "xss": true,
}

// mergedInitialisms returns defaultInitialisms + extra (each extra lower-cased) as
// a fresh map, so the package-level default is never mutated.
func mergedInitialisms(extra []string) map[string]bool {
	out := maps.Clone(defaultInitialisms)
	for _, e := range extra {
		out[strings.ToLower(e)] = true
	}
	return out
}

// Marshal renders a loaded, resolved schema (and its import closure) as formatted,
// type-checked Go source. The schema must be completed (aliases resolved,
// inheritance linearized) AND source-backed — i.e. loaded via schema.Load,
// schema.LoadString, or schema.LoadSourcesWithEntry. A schema built
// programmatically via schema.Builder without retained source content has a nil
// Sources(); Marshal returns an error for it, because the embedded SerializedModel
// and its round-trip self-check require the source.
func Marshal(s *schema.Schema, opts ...Option) ([]byte, error) {
	cfg := config{}
	for _, o := range opts {
		o(&cfg)
	}
	pkg := cfg.packageName
	if pkg == "" {
		pkg = goPackageName(s.Name())
	}
	inits := mergedInitialisms(cfg.initialisms) // default golint set + injected
	names, err := buildNameTable(s, inits)
	if err != nil {
		return nil, err
	}
	g := &generator{
		schema:       s,
		pkg:          pkg,
		names:        names,
		initialisms:  inits,
		buf:          &bytes.Buffer{},
		edgeNames:    map[*schema.Relation]string{},
		dtFieldNames: map[*schema.Property]string{},
	}
	data, err := g.generate()
	if err != nil {
		return nil, err
	}
	if err := verifyRoundTrip(s); err != nil { // guarantee the embedded model re-loads
		return nil, err
	}
	return data, nil
}

// verifyRoundTrip re-loads the embedded SerializedModel and confirms it produces a
// schema with the same StructuralHash, making the embedded provenance a guaranteed
// re-loadable model rather than an unverified claim. It re-loads EXACTLY what
// emitSerializedModel embeds — the SAME module-root-relative keys (via sourceKey
// against the schema's recorded ModuleRoot): single source via LoadString;
// multi-source via LoadSourcesWithEntry with the relative entry key, moduleRoot "."
// (a bare `import "x.yammm"` is module-style and requires a module root; the keys
// are root-relative, so registration and import resolution join them against the
// same canonicalized "." regardless of what cwd is), and WithSourcesOnly — the
// re-load is HERMETIC by construction: an import that misses the embedded map
// fails the load rather than being silently satisfied by a same-named file on
// disk. StructuralHash is path-independent, so the re-load's SourceIDs do not
// affect the comparison — but the canonicalized "." is what lands in every TypeID
// of a schema re-loaded that way, which is why the emitted recipes recommend
// WithSyntheticRoot instead. A failure is a generator bug surfaced as an error.
//
// The uniform SerializedSources/SerializedEntry shape is then checked on top, for
// both source counts, because it is emitted on both arms. That check carries no
// synthetic root: relative imports need the importing source's canonical path,
// which no synthetic identity has, so a synthetic root here would fail generation
// for a schema shape the DSL supports. Coverage of the recommended root lives in
// this package's tests instead.
func verifyRoundTrip(s *schema.Schema) error {
	srcs := s.Sources()
	ids := srcs.SourceIDs()
	entry := s.SourceID()
	root := s.ModuleRoot()
	want := schema.StructuralHash(s)
	ctx := context.Background()
	switch len(ids) {
	case 0:
		return errors.New("gogen: schema is not source-backed; Marshal requires a schema loaded via Load/LoadString/LoadSourcesWithEntry")
	case 1:
		content, ok := srcs.ContentBySource(ids[0])
		if !ok {
			return errors.New("gogen: schema source content unavailable")
		}
		got, res := schema.LoadString(ctx, string(content), sourceKey(root, entry, ids[0]))
		if res.HasErrors() {
			return fmt.Errorf("gogen: embedded SerializedModel does not re-load: %w", res.Err())
		}
		if h := schema.StructuralHash(got); h != want {
			return fmt.Errorf("gogen: SerializedModel round-trip hash mismatch (got %s, want %s)", h, want)
		}
	default:
		m := make(map[string][]byte, len(ids))
		for _, id := range ids {
			content, ok := srcs.ContentBySource(id)
			if !ok {
				return fmt.Errorf("gogen: source %s content unavailable", id)
			}
			m[sourceKey(root, entry, id)] = content
		}
		got, res := schema.LoadSourcesWithEntry(ctx, m, sourceKey(root, entry, entry), ".", schema.WithSourcesOnly())
		if res.HasErrors() {
			return fmt.Errorf("gogen: embedded SerializedModel does not re-load: %w", res.Err())
		}
		if h := schema.StructuralHash(got); h != want {
			return fmt.Errorf("gogen: SerializedModel round-trip hash mismatch (got %s, want %s)", h, want)
		}
	}
	return verifyUniformRoundTrip(ctx, srcs, ids, entry, root, want)
}

// verifyUniformRoundTrip re-loads the emitted SerializedSources map under its
// emitted SerializedEntry, so the uniform shape is not the one emitted surface
// with no self-check. It mirrors the multi-source arm exactly — module root ".",
// hermetic — because that is what the emitted accessor's own keys join against.
func verifyUniformRoundTrip(ctx context.Context, srcs *schema.Sources, ids []location.SourceID, entry location.SourceID, root, want string) error {
	m := make(map[string][]byte, len(ids))
	for _, id := range ids {
		content, ok := srcs.ContentBySource(id)
		if !ok {
			return fmt.Errorf("gogen: source %s content unavailable", id)
		}
		m[sourceKey(root, entry, id)] = content
	}
	got, res := schema.LoadSourcesWithEntry(ctx, m, sourceKey(root, entry, entry), ".", schema.WithSourcesOnly())
	if res.HasErrors() {
		return fmt.Errorf("gogen: embedded SerializedSources does not re-load: %w", res.Err())
	}
	if h := schema.StructuralHash(got); h != want {
		return fmt.Errorf("gogen: SerializedSources round-trip hash mismatch (got %s, want %s)", h, want)
	}
	return nil
}

// generator accumulates emitted declarations into buf, then assembles and
// formats the final file.
type generator struct {
	schema       *schema.Schema
	pkg          string
	names        *nameTable
	initialisms  map[string]bool // effective acronym set (default golint + injected)
	buf          *bytes.Buffer
	needsTime    bool                        // set when any emitted field is a time.Time
	edges        []edgeRec                   // one per DECLARED association (each emitted as one EDGE_ struct)
	edgeNames    map[*schema.Relation]string // association -> owner-qualified EDGE_ Go name (shared via relation ptr)
	dtFieldNames map[*schema.Property]string // DataType-typed field (type or edge prop) -> its DataType Go name
}

// edgeRec carries what emitEdgeStructs needs to emit one EDGE_ struct: the
// association (for its edge properties and FieldName) and the resolved target type
// (for the Where primary-key block). The EDGE_ Go name lives in generator.edgeNames,
// and the Go type of every DataType-typed field lives in generator.dtFieldNames —
// both keyed by pointer and resolved in their DECLARING schema by the pre-passes
// (registerEdges / registerDataTypeFields), so emission itself needs no notion of a
// "current schema".
type edgeRec struct {
	rel    *schema.Relation
	target *schema.Type
}

// generate emits the body, prepends header/package/imports, formats, and
// type-checks. A format or type-check failure is a generator bug, surfaced as an
// error rather than emitted as broken Go.
func (g *generator) generate() ([]byte, error) {
	if err := g.registerDataTypeFields(); err != nil {
		return nil, err
	}
	if err := g.registerEdges(); err != nil {
		return nil, err
	}
	if err := g.emitNamedTypes(); err != nil {
		return nil, err
	}
	if err := g.emitTypes(); err != nil {
		return nil, err
	}
	if err := g.emitEdgeStructs(); err != nil {
		return nil, err
	}
	if err := g.emitGraph(); err != nil {
		return nil, err
	}
	if err := g.emitSerializedModel(); err != nil {
		return nil, err
	}

	var out bytes.Buffer
	out.WriteString(generatedHeader)
	fmt.Fprintf(&out, "package %s\n\n", g.pkg)
	if g.needsTime {
		out.WriteString("import \"time\"\n\n")
	}
	out.Write(g.buf.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gogen: generated source did not parse: %w", err)
	}
	if err := typeCheck(formatted); err != nil {
		return nil, fmt.Errorf("gogen: generated source did not type-check: %w", err)
	}
	return formatted, nil
}

// typeCheck parses and type-checks src with go/types. It catches the semantic
// failures format.Source cannot: duplicate type/field declarations, unused
// imports, and undefined references. The generated code imports at most "time"
// (used only as the time.Time field type), so a hermetic stub importer resolves
// it — no Go toolchain, GOROOT, or build cache is needed at runtime. This matters
// because Marshal runs inside the distributed yammm CLI binary, which may execute
// where importer.Default() (gc export data) or the source importer (GOROOT/src)
// would have nothing to read.
func typeCheck(src []byte) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "gen.go", src, parser.AllErrors)
	if err != nil {
		return fmt.Errorf("parsing generated source: %w", err)
	}
	conf := types.Config{Importer: timeImporter{}}
	if _, err := conf.Check(f.Name.Name, fset, []*ast.File{f}, nil); err != nil {
		return fmt.Errorf("checking generated source: %w", err)
	}
	return nil
}

// timeImporter is a hermetic types.Importer for the single import gogen can emit:
// "time". The generated code uses time only as the time.Time field type (never a
// method or function), so a synthetic package exposing an opaque Time type fully
// satisfies type-checking. Resolving any other path is a generator bug, surfaced
// explicitly. Being toolchain-free, it lets Marshal type-check identically in any
// environment (CI container, scratch image) and still flags unused imports,
// duplicate declarations, and undefined references.
type timeImporter struct{}

func (timeImporter) Import(path string) (*types.Package, error) {
	if path != "time" {
		return nil, fmt.Errorf("gogen: generated code imported %q; the generator emits only \"time\"", path)
	}
	pkg := types.NewPackage("time", "time")
	named := types.NewNamed(types.NewTypeName(token.NoPos, pkg, "Time", nil), types.NewStruct(nil, nil), nil)
	pkg.Scope().Insert(named.Obj())
	pkg.MarkComplete()
	return pkg, nil
}
